config/routes.rb
Rails.application.routes.draw do
  # get 'technology_items/new'
  # get 'technology_items/create'
  # get 'technology_items/edit'
  # get 'technology_items/update'
  # get 'technology_items/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'projects/index'
  # get 'projects/show'
  # get 'projects/new'
  # get 'projects/create'
  # get 'projects/edit'
  # get 'projects/update'
  # get 'projects/destroy'
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks], controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  get 'about', to: 'pages#about', as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  resources :projects
  resources :resumes do
    member do
      get 'download', to: 'resumes#download_resume'
    end


    resources :educations
    resources :experiences
  end
  resources :technology_items, only: [:new, :create, :edit, :update, :destroy]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
end

app/models/technology_item.rb
class TechnologyItem < ApplicationRecord
  has_one_attached :logo

  has_many :project_technologies, dependent: :destroy
  has_many :projects, through: :project_technologies

  validates :name, presence: true
  validates :category, presence: true

  enum category: { frontend: "frontend", backend: "backend", tools: "tools" }

  validates :order_position, uniqueness: { scope: :category, message: "La position doit être unique par catégorie." }
end

app/controllers/technology_items_controller.rb
class TechnologyItemsController < ApplicationController
  def new
    @technology_item = TechnologyItem.new

    @title = "New Skills"
    @subtitle = "On en apprend toujours. 🤓"
  end

  def create
    @technology_item = TechnologyItem.new(technology_item_params)

    if @technology_item.save
      redirect_to root_path, notice: "Nouvelle technologie ajoutée avec succès."
    else
      render :new, alert: "Erreur lors de l'ajout de la technologie."
    end
  end

  def edit
    @technology_item = TechnologyItem.find(params[:id])

    @title = "Modifier une tech"
    @subtitle = "Un correctif pour un meilleur impact ! 🔧"
  end

  def update
    @technology_item = TechnologyItem.find(params[:id])

    if @technology_item.update(technology_item_params)
      redirect_to root_path, notice: "Technologie modifiée avec succès."
    else
      render :edit, alert: "Erreur lors de la modification de la technologie."
    end
  end

  def destroy
    @technology_item = TechnologyItem.find(params[:id])

    if @technology_item.destroy
      redirect_to root_path, notice: "Technologie supprimée avec succès."
    else
      redirect_to root_path, alert: "Erreur lors de la suppression de la technologie."
    end
  end

  private

  def technology_item_params
    params.require(:technology_item).permit(:name, :link, :logo, :category, :order_position)
  end
end

app/views/technology_items/create.html.erb
<h1>TechnologyItems#create</h1>
<p>Find me in app/views/technology_items/create.html.erb</p>

app/views/technology_items/destroy.html.erb
<h1>TechnologyItems#destroy</h1>
<p>Find me in app/views/technology_items/destroy.html.erb</p>

app/views/technology_items/edit.html.erb
<div class="formulaire-conteneur" id="first-section">

  <h2><span>M</span>ettre à jour les informations de la tech</h2>


  <%= form_with(model: @technology_item, local: true) do |form| %>
    <div class="field">
      <%= form.label :name, "Nom de la technologie" %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="field">
      <%= form.label :category, "Catégorie" %>
      <%= form.select :category, TechnologyItem.categories.keys.map { |c| [c.humanize, c] }, prompt: "Choisir une catégorie", required: true %>
    </div>

    <div class="field">
      <%= form.label :link, "Lien vers la technologie" %>
      <%= form.url_field :link %>
    </div>

    <div class="field">
      <%= form.label :order_position, "Position d'affichage" %>
      <%= form.number_field :order_position, min: 1 %>
    </div>

    <div class="field">
      <%= form.label :logo, "Logo de la technologie" %>
      <%= form.file_field :logo, accept: "image/*" %>
    </div>

    <div class="actions">
      <%= form.submit "Mettre à jour", class: "button button-update" %>

      <%# Bouton Annuler %>
      <%= link_to "Annuler", root_path, class: "button button-cancel", onclick: "window.history.back();", onclick: "window.history.back();" %>

    </div>
  <% end %>

  <!-- Bouton de suppression avec confirmation -->
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Supprimer', technology_item_path(@technology_item),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "button button-delete" %>
  <% end %>

</div>

app/views/technology_items/new.html.erb
<div class="formulaire-conteneur" id="first-section">

  <h2><span>E</span>nregistrer une nouvelle tech</h2>


  <%= form_with(model: @technology_item, url: technology_items_path, local: true) do |form| %>

    <div class="field">
      <%= form.label :name, "Nom de la technologie" %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="field">
      <%= form.label :category, "Catégorie" %>
      <%= form.select :category, TechnologyItem.categories.keys.map { |c| [c.humanize, c] }, prompt: "Choisir une catégorie", required: true %>
    </div>

    <div class="field">
      <%= form.label :link, "Lien vers la technologie" %>
      <%= form.url_field :link %>
    </div>

    <div class="field">
      <%= form.label :order_position, "Position d'affichage" %>
      <%= form.number_field :order_position, min: 1 %>
    </div>

    <div class="field">
      <%= form.label :logo, "Logo de la technologie" %>
      <%= form.file_field :logo, accept: "image/*" %>
    </div>

    <div class="actions">
      <%= form.submit "Ajouter Technologie", class: "button" %>
    </div>

    <%# Bouton Annuler %>
    <%= link_to "Annuler", root_path, class: "button button-cancel", onclick: "window.history.back();" %>
  <% end %>

</div>

app/views/technology_items/update.html.erb
<h1>TechnologyItems#update</h1>
<p>Find me in app/views/technology_items/update.html.erb</p>