config/routes.rb
Rails.application.routes.draw do
  # get 'technology_items/new'
  # get 'technology_items/create'
  # get 'technology_items/edit'
  # get 'technology_items/update'
  # get 'technology_items/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'projects/index'
  # get 'projects/show'
  # get 'projects/new'
  # get 'projects/create'
  # get 'projects/edit'
  # get 'projects/update'
  # get 'projects/destroy'
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks], controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  get 'about', to: 'pages#about', as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  resources :projects
  resources :resumes do
    member do
      get 'download', to: 'resumes#download_resume'
    end


    resources :educations
    resources :experiences
  end
  resources :technology_items, only: [:new, :create, :edit, :update, :destroy]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
end

app/views/shared/_contact.html.erb
<section class="section-contact" data-aos="zoom-in-up" data-aos-once="true">


  <div class="form-contact">
    <%= form_with model: @contact, url: contacts_path, local: true, html: { class: "custom-form" } do |form| %>
      <h2><span>F</span>ormulaire de contact</h2>

      <div class="contact-row">
        <div class="contact-input">
          <%= form.text_field :last_name, placeholder: "Votre nom", required: true %>
        </div>

        <div class="contact-input">
          <%= form.email_field :email, placeholder: "Adresse email", required: true %>
        </div>
      </div>


      <div class="contact-input">
        <%= form.text_area :message, placeholder: "Votre message", class: "textarea", required: true %>
      </div>

      <%= form.submit "Envoyer.", class: "button-submit" %>
    <% end %>
  </div>


</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" data-aos="zoom-in" data-aos-once="true">
  <div class="footer-links">
    <%= link_to "https://www.linkedin.com/in/benalta7892", target: "_blank" do %>
      <i class="fab fa-linkedin"></i>
    <% end %>

    <%= link_to "https://github.com/benalta7892", target: "_blank" do %>
      <i class="fab fa-github"></i>
    <% end %>

  </div>
  <div class="footer-copyright">
    <p>📍 Localisation : Paris</p>
  </div>
</div>

app/views/shared/_hero.html.erb
<div class="hero-content">

  <div class="darkmode-toggle">
    <input type="checkbox" id="btn-darkmode-toggle" class="input-btn-darkmode">
    <label for="btn-darkmode-toggle" class="label-darkmode" id="dark-mode-toggle">

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="sun">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
      </svg>

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="moon">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
      </svg>

    </label>
  </div>


  <div class="hero-top-content" data-aos="zoom-in" data-aos-once="true">
    <h1><span>B</span>enoit<br>
      <span>A</span>lexandre</h1>
    <p class="subtitle">Développeur web - Full Stack</p>
    <%= link_to "Mon CV.", download_resume_path(@resume), class: "button-download", target: "_blank" %>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "Accéder à l'espace Admin", rails_admin_path, target: "_blank", class: "button-download" %>
    <% end %>

  </div>
  <div class="links">
    <%= link_to "https://www.linkedin.com/in/benalta7892", class: "link", target: "_blank" do %>
      <%= image_tag "linkedin.png", alt: "Linkedin" %>
    <% end %>

    <%= link_to "https://github.com/benalta7892", class: "link", target: "_blank" do %>
      <%= image_tag "github.png", alt: "Github" %>
    <% end %>
  </div>

  <%= link_to "#first-section", id: "scroll-down" do %>
    <i class="fa-solid fa-caret-down"></i>
  <% end %>


</div>

app/views/shared/_navbar.html.erb
<nav data-aos="zoom-in" data-aos-once="true">

  <div class="logo-container">
    <%= link_to root_path, class: "logo", aria: { label: "visit homepage", current: "page" } do %>
      <%= cl_image_tag "BenoitAlexandreLogo_ci6r6n", alt: "Logo de Benoit Alexandre", class: "logo-img logo-light" %>
      <%= cl_image_tag "BenoitAlexandreLogoDark_cgs5lq", alt: "Logo de Benoit Alexandre (Mode Sombre)", class: "logo-img logo-dark" %>
    <% end %>
  </div>


  <div class="nav-links">
    <%= link_to 'Accueil.', root_path, aria: { current: "page" } %>
    <%= link_to 'À propos.', about_path %>
    <%= link_to 'Portfolio.', projects_path %>
    <%= link_to 'Contact.', new_contact_path %>
  </div>

  <div class="main-navlinks">
    <button class="hamburger" type="button" aria-label="Toggle navigation" aria-expanded="false">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>

</nav>

app/views/shared/_smallbanner.html.erb
<div class="small-hero-content">

  <div class="darkmode-toggle">
    <input type="checkbox" id="btn-darkmode-toggle" class="input-btn-darkmode">
    <label for="btn-darkmode-toggle" class="label-darkmode" id="dark-mode-toggle">

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="sun">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
      </svg>

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="moon">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
      </svg>

    </label>
  </div>


  <div class="small-hero-top-content" data-aos="zoom-in" data-aos-once="true">
    <h1 aria-label="Porsche, set free."><%= title %></h1>
    <p class="subtitle"><%= subtitle %></p>
    <% if @resume %>
      <%= link_to "Mon CV.", download_resume_path(@resume), class: "button-download", target: "_blank" %>
    <% end %>
  </div>


  <div class="links">
    <%= link_to "https://www.linkedin.com/in/benalta7892", class: "link", target: "_blank" do %>
      <%= image_tag "linkedin.png", alt: "Linkedin" %>
    <% end %>

    <%= link_to "https://github.com/benalta7892", class: "link", target: "_blank" do %>
      <%= image_tag "github.png", alt: "Github" %>
    <% end %>
  </div>

  <%= link_to "#first-section", id: "scroll-down" do %>
    <i class="fa-solid fa-caret-down"></i>
  <% end %>


</div>