config/routes.rb
Rails.application.routes.draw do
  # get 'technology_items/new'
  # get 'technology_items/create'
  # get 'technology_items/edit'
  # get 'technology_items/update'
  # get 'technology_items/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'projects/index'
  # get 'projects/show'
  # get 'projects/new'
  # get 'projects/create'
  # get 'projects/edit'
  # get 'projects/update'
  # get 'projects/destroy'
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks], controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  get 'about', to: 'pages#about', as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  resources :projects
  resources :resumes do
    member do
      get 'download', to: 'resumes#download_resume'
    end


    resources :educations
    resources :experiences
  end
  resources :technology_items, only: [:new, :create, :edit, :update, :destroy]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
end

app/views/pages/about.html.erb
<br>
<a id="first-section"></a>
<% if request.referer == root_url %>
  <%= link_to '<i class="fa-solid fa-arrow-left"></i> Retour'.html_safe, request.referer, class: "button button-back-about", data: { turbo: false } %>
<% end %>


<div class="cv-container">
  <div class="cv-description" data-aos="fade-up" data-aos-once="true">
    <p><%= @resume.description[0] %></p>
    <p><%= @resume.description[1] %></p>
  </div>

  <div class="cv-download" data-aos="fade-up">
    <%= cl_image_tag @resume.picture.key, alt: "Image du CV" %>

    <div data-controller="popover" data-action="mouseenter->popover#show mouseleave->popover#hide">
      <%= link_to download_resume_path(@resume), class: "button-download", target: "_blank", rel: "noopener noreferrer" do %> <!-- Lien de téléchargement -->
        <i class="fa-solid fa-download" style="color: #000000;"></i>
      <% end %>

      <!-- Contenu du popover pour le bouton de téléchargement -->
      <template data-popover-target="content">
        <div data-popover-target="card" class="popover-content">
          <p>Mon CV</p>
        </div>
      </template>
    </div>
  </div>

</div>

<!-- Section Éducation -->
<div class="section-parcours" data-aos="fade-up" data-aos-once="true">
  <h2><span>C</span>onfirmé par des diplômes</h2>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "Ajouter une nouvelle éducation", new_resume_education_path(@resume.id), class: "button", data: { turbo: false } %>
  <% end %>
  <div class="box-timeline parcours-timeline">
    <div class="ligne parcours-ligne"></div>
    <% @educations.each_with_index do |education, index| %>
      <div class="rond parcours-rond r<%= index + 1 %>" data-anim="<%= index + 1 %>">
        &#127891; <!-- Icône pour les éducations -->
      </div>
      <div class="box parcours-box b<%= index + 1 %> <%= index.even? ? 'left' : 'right' %>" data-anim="<%= index + 1 %>">
        <p class="date"><%= education.start_date.strftime('%m/%Y') %> - <%= education.end_date ? education.end_date.strftime('%m/%Y') : "À ce jour" %></p>
        <h2><%= education.diploma_name %></h2>
        <p><%= education.institution_name %></p>
        <p><%= education.location %></p>

        <!-- Affichage des boutons Modifier et Supprimer si l'utilisateur est admin -->
        <% if user_signed_in? && current_user.admin? %>
          <div class="editOrDeleteBtn education-btn">
            <%= link_to 'Modifier', edit_resume_education_path(@resume, education), class: 'button button-edit', data: { turbo: false } %>
            <%= link_to 'Supprimer', resume_education_path(@resume, education),
                data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette éducation ?" },
                class: "button button-delete" %>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>
</div>

<% if false %>
  <!-- Section Expérience -->
  <div class="section-experiences" data-aos="fade-up" data-aos-once="true">
    <h2><span>E</span>xperiences Professionnelles</h2>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "Ajouter une nouvelle expérience", new_resume_experience_path(@resume.id), class: "button" %>
    <% end %>
    <div class="box-timeline experience-timeline">
      <div class="ligne experience-ligne"></div>
      <% @experiences.each_with_index do |experience, index| %>
        <div class="rond experience-rond r<%= index + 1 %>" data-anim="<%= index + 1 %>">
          &#128188; <!-- Icône pour les expériences -->
        </div>
        <div class="box experience-box b<%= index + 1 %> <%= index.even? ? 'left' : 'right' %>" data-anim="<%= index + 1 %>">
          <p class="date"><%= experience.start_date.strftime('%m/%Y') %> - <%= experience.end_date ? experience.end_date.strftime('%m/%Y') : "À ce jour" %></p>
          <h2><%= experience.job_title %></h2>
          <p><%= experience.company_name %></p>
          <p><%= experience.location %></p>

          <!-- Affichage des boutons Modifier et Supprimer si l'utilisateur est admin -->
          <% if user_signed_in? && current_user.admin? %>
            <div class="editOrDeleteBtn education-btn">
              <%= link_to 'Modifier', edit_resume_experience_path(@resume, experience), class: 'button button-edit' %>
              <%= link_to 'Supprimer', resume_experience_path(@resume, experience),
                data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette éducation ?" },
                class: "button button-delete" %>
            </div>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>
<% end %>


<section class="carousel-logos">
  <div class="carousel" id="carousel" role="region" aria-label="Logo Carousel">

    <div class="carousel-mask-left"></div>
    <div class="carousel-mask-right"></div>

    <div class="carousel-container" id="carouselContainer" role="list">
      <!-- Logos Front-End -->
      <% @frontend_technologies.each do |tech| %>
        <% if tech.logo.attached? %>
          <%= cl_image_tag tech.logo.key, alt: tech.name, width: 100, height: 100, class: "carousel-logo" %>
        <% else %>
          <p>Image manquante pour <%= tech.name %>.</p>
        <% end %>
      <% end %>

      <!-- Logos Back-End -->
      <% @backend_technologies.each do |tech| %>
        <% if tech.logo.attached? %>
          <%= cl_image_tag tech.logo.key, alt: tech.name, width: 100, height: 100, class: "carousel-logo" %>
        <% else %>
          <p>Image manquante pour <%= tech.name %>.</p>
        <% end %>
      <% end %>

      <!-- Logos Outils -->
      <% @tools.each do |tool| %>
        <% if tool.logo.attached? %>
          <%= cl_image_tag tool.logo.key, alt: tool.name, width: 100, height: 100, class: "carousel-logo" %>
        <% else %>
          <p>Image manquante pour <%= tool.name %>.</p>
        <% end %>
      <% end %>
    </div>

  </div>
</section>

app/views/pages/home.html.erb
<%# browser-sync start --proxy "localhost:3000" --files "app/views/**/*.erb, app/assets/stylesheets/**/*.css, app/assets/javascripts/**/*.js, app/models/**/*.rb, app/controllers/**/*.rb" --no-notify --watch --watch-options-ignoreInitial --watch-options-awaitWriteFinish %>
<br>
<a id="first-section"></a>

<div class="custom-cursor"></div>

<section class="section-presentation"  data-aos="fade-up" data-aos-once="true">

  <div class="text-content-presentation">

    <%= cl_image_tag @admin_user.avatar.key, alt: "Photo de profil" %>

    <h2><span>B</span>ienvenue</h2>
    <p>
      Je suis <span>développeur web full stack</span> avec une expertise solide
      dans le développement de projets complets, de la conception au déploiement.
      Explorez mon profil avec un regard sur comment je peux mettre mes compétences
      au service de vos objectifs. 🙂
    </p>

  </div>

  <%= link_to "Plus d'infos.", about_path, data: { turbo: false } %>


</section>


<section class="section-skills" data-aos="fade-up" data-aos-once="true">

  <h2><span>S</span>tack des technologies maîtrisées</h2>

  <%# Lien pour ajouter une nouvelle technologie si l'utilisateur est administrateur %>
  <% if user_signed_in? && current_user.admin? %>
    <div class="add-tech-link">
      <%= link_to "Ajouter une nouvelle technologie", new_technology_item_path, class: "button button-add-tech", data: { turbo: false } %>
    </div>
  <% end %>


  <div class="skills-content">


    <div class="skill-category">
      <h2><span>F</span>ront-End</h2>
      <div class="logos">
        <% @frontend_technologies.each do |tech| %>
          <% if tech.logo.attached? && tech.link.present? %>
            <div data-controller="popover" data-action="mouseenter->popover#show mouseleave->popover#hide">
              <%= link_to cl_image_tag(tech.logo.key, alt: tech.name, width: 100, height: 100), tech.link, target: "_blank", data: { turbo: false } %>
              <template data-popover-target="content">
                <div data-popover-target="card" class="popover-content <%= 'admin-visible' if user_signed_in? && current_user.admin? %>">
                  <p><%= tech.name %></p>
                </div>
              </template>

              <%# Boutons d'administration %>
              <% if user_signed_in? && current_user.admin? %>
                <div class="admin-buttons">
                  <%= link_to edit_technology_item_path(tech), class: "button button-edit", data: { turbo: false } do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>

                  <%= link_to technology_item_path(tech),
                        data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette technologie ?" },
                        class: "button button-delete" do %>
                    <i class="fa-regular fa-trash-can"></i>
                  <% end %>

                </div>
              <% end %>

            </div>
          <% else %>
            <p>Information manquante pour la technologie <%= tech.name %>.</p>
          <% end %>


        <% end %>
      </div>
    </div>


    <div class="skill-category">
      <h2><span>B</span>ack-End</h2>
      <div class="logos">
        <% @backend_technologies.each do |tech| %>
          <% if tech.logo.attached? && tech.link.present? %>
            <div data-controller="popover" data-action="mouseenter->popover#show mouseleave->popover#hide">
              <%= link_to cl_image_tag(tech.logo.key, alt: tech.name, width: 100, height: 100), tech.link, target: "_blank", data: { turbo: false } %>
              <template data-popover-target="content">
                <div data-popover-target="card" class="popover-content <%= 'admin-visible' if user_signed_in? && current_user.admin? %>">
                  <p><%= tech.name %></p>
                </div>
              </template>

              <%# Boutons d'administration %>
              <% if user_signed_in? && current_user.admin? %>
                <div class="admin-buttons">
                  <%= link_to edit_technology_item_path(tech), class: "button button-edit", data: { turbo: false } do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>

                  <%= link_to technology_item_path(tech),
                    data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette technologie ?" },
                    class: "button button-delete" do %>
                    <i class="fa-regular fa-trash-can"></i>
                  <% end %>
                </div>
              <% end %>

            </div>
          <% else %>
            <p>Information manquante pour la technologie <%= tech.name %>.</p>
          <% end %>
        <% end %>
      </div>
    </div>


    <div class="skill-category">
      <h2><span>O</span>utils</h2>
      <div class="logos">
        <% @tools.each do |tool| %>
          <% if tool.logo.attached? && tool.link.present? %>
            <div data-controller="popover" data-action="mouseenter->popover#show mouseleave->popover#hide">
              <%= link_to cl_image_tag(tool.logo.key, alt: tool.name, width: 100, height: 100), tool.link, target: "_blank", data: { turbo: false } %>
              <template data-popover-target="content">
                <div data-popover-target="card" class="popover-content <%= 'admin-visible' if user_signed_in? && current_user.admin? %>">
                  <p><%= tool.name %></p>
                </div>
              </template>

              <%# Boutons d'administration %>
              <% if user_signed_in? && current_user.admin? %>
                <div class="admin-buttons">
                  <%= link_to edit_technology_item_path(tool), class: "button button-edit", data: { turbo: false } do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>

                  <%= link_to technology_item_path(tool),
                    data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet outil ?" },
                    class: "button button-delete" do %>
                    <i class="fa-regular fa-trash-can"></i>
                  <% end %>
                </div>
              <% end %>

            </div>
          <% else %>
            <p>Information manquante pour l'outil <%= tool.name %>.</p>
          <% end %>
        <% end %>
      </div>
    </div>


  </div>

</section>


<section class="section-portolio" data-aos="fade-up" data-aos-once="true">
  <h2><span>P</span>rojets phares</h2>


  <div class="carousel-portfolio" data-controller="carousel">

    <button data-action="click->carousel#previous" class="btn-carousel left">
      <%= cl_image_tag "arrowL_y08p76.png", class: "custom-arrow",  alt: 'Flèche de gauche' %>
    </button>

    <div class="carousel-items-portfolio">
      <% @projects.each_with_index do |project, index| %>
        <%= link_to project_path(project), class: "carousel-slide #{'hidden' unless index == 0}", data: { action: "click->carousel#saveCurrentIndex", carousel_target: "slide", turbo: false } do %>
          <div class="carousel-image-container">
            <% if project.pictures.attached? %>
              <%= cl_image_tag project.pictures.first.key, class: "carousel-image" %>
            <% else %>
              <p>Aucune image disponible pour ce projet.</p>
            <% end %>
            <i class="fa-solid fa-arrow-up-right-from-square"></i>

          </div>
          <div class="project-title">
            <%= project.title %>
          </div>
        <% end %>
      <% end %>
    </div>


    <button data-action="click->carousel#next" class="btn-carousel right">
      <%= cl_image_tag "arrowR_v3vouj.png", class: "custom-arrow",  alt: 'Flèche de droite' %>
    </button>


  </div>

  <%= link_to 'En voir plus.', projects_path, data: { turbo: false }, class: "link-more" %>

  <div class="contributions-container">
    <div id="gh" data-login="Benalta7892" class="contributions"></div>
  </div>

</section>